In [1]:
import numpy as np


# 1. Многомерный обьект массива

## 1.2 Создание массива

<img src="https://ucarecdn.com/09b174e8-e8b2-4c10-990c-570057daf8c8/" alt="drawing" width="400"/>.
<img src="https://ucarecdn.com/a659ae99-e9f5-4523-be7d-eae05bfbf195/" alt="drawing" width="600"/>.
<img src="https://ucarecdn.com/06e69802-f635-45dc-a3a9-95337ce1a6b8/" width="800"/>.
<img src="https://ucarecdn.com/1450cdcd-22ac-40e0-86ef-05ff27bf8510/" width="400"/>.

In [2]:
a = np.array([1,2,3])
b = np.array(([1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]), dtype=np.float64)
c = np.zeros((3,5))
d = np.ones((1,5))
print(a)
print(b)
print(c)
print(d)

[1 2 3]
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]]


In [3]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.arange(1,5)

array([1, 2, 3, 4])

In [5]:
print(np.arange(0,1 + 0.1,0.1))


[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [6]:
print(np.linspace(0,1)) # num (необязательный): Количество элементов в массиве. По умолчанию 50.

[0.         0.02040816 0.04081633 0.06122449 0.08163265 0.10204082
 0.12244898 0.14285714 0.16326531 0.18367347 0.20408163 0.2244898
 0.24489796 0.26530612 0.28571429 0.30612245 0.32653061 0.34693878
 0.36734694 0.3877551  0.40816327 0.42857143 0.44897959 0.46938776
 0.48979592 0.51020408 0.53061224 0.55102041 0.57142857 0.59183673
 0.6122449  0.63265306 0.65306122 0.67346939 0.69387755 0.71428571
 0.73469388 0.75510204 0.7755102  0.79591837 0.81632653 0.83673469
 0.85714286 0.87755102 0.89795918 0.91836735 0.93877551 0.95918367
 0.97959184 1.        ]


In [7]:
np.linspace(0,5,9)

array([0.   , 0.625, 1.25 , 1.875, 2.5  , 3.125, 3.75 , 4.375, 5.   ])

In [8]:
np.full((3,3),7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [9]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## 1.3 Создание массива часть 2

In [10]:
np.ones([3,2])

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

<img src="https://ucarecdn.com/c6cf7ceb-9a35-4001-9410-2259da43d47c/" width="600"/>.
<img src="https://ucarecdn.com/c544842a-29cd-48d8-b4a6-1d139228f5d3/" width="300"/>.

In [11]:
print(b)
print(np.ndim(b))
print(np.shape(b))
print(np.size(b))

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]
2
(4, 4)
16


In [12]:
print(np.eye(5,3)) # Еденичная матрица
print(np.eye(3,3)) # аналогично identity
print(np.identity(3)) # создает квадратную матрицу с единицами на главной диагонали и нулями в остальных местах.
# В отличие от numpy.identity,  numpy.eye позволяет создавать матрицы с единичной диагональю 
# произвольной размерности и выполнять сдвиг этой диагонали относительно главной диагонали.
print('')
print(np.eye(5,k=2))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [13]:
np.random.rand( 3,3 )

array([[0.39487312, 0.85702033, 0.54144958],
       [0.63080058, 0.59712907, 0.35977549],
       [0.99112653, 0.66121955, 0.69840331]])

In [14]:
np.random.randint(10) # случайное число от 0 до 10 (целое)

6

In [15]:
print(np.random.randint(1,10, size=5))

[3 6 2 5 8]


In [16]:
print(np.random.randint(1,10, size=(3,3)))

[[8 5 2]
 [9 2 7]
 [4 4 4]]


In [17]:
small_arr = np.array([[1,2],[3,4]])
small_arr

array([[1, 2],
       [3, 4]])

In [18]:
print(np.tile(small_arr,reps=3))

[[1 2 1 2 1 2]
 [3 4 3 4 3 4]]


In [19]:
print(np.tile(small_arr,reps=(3,3)))

[[1 2 1 2 1 2]
 [3 4 3 4 3 4]
 [1 2 1 2 1 2]
 [3 4 3 4 3 4]
 [1 2 1 2 1 2]
 [3 4 3 4 3 4]]


## 1.4 Типы Данных

int(16-64), float(16-64), complex(64-128), bool, string, object (используется для хранения произвольных объектов Python в массивах NumPy)

In [20]:
print(b*0.2)
print(np.dtype(b[0][0]))
b.dtype

[[0.2 0.4 0.6 0.8]
 [1.  1.2 1.4 1.6]
 [1.8 2.  2.2 2.4]
 [2.6 2.8 3.  3.2]]
float64


dtype('float64')

In [21]:
# array.astype(dtype, order='K', casting='unsafe', subok=True, copy=True)
b_int = (b*0.2).astype(np.int64)
print(b_int)
b.dtype

[[0 0 0 0]
 [1 1 1 1]
 [1 2 2 2]
 [2 2 3 3]]


dtype('float64')

Задача: Предположим, у вас есть два датасета с данными о температуре и влажности. Каждый датасет представлен в виде двумерного массива, где строки представляют дни, а столбцы представляют конкретные моменты времени в течение дня. Тип данных - int. Но вам нужно изменить их на float.

In [22]:
# put your python code here
import numpy as np

# Датасет температуры (тип данных: int)
temp_data = np.array([[22, 25, 24, 23, 21],
                      [20, 18, 19, 22, 24]])

# Датасет влажности (тип данных: int)
humid_data = np.array([[45, 50, 48, 52, 47],
                       [45, 48, 50, 51, 53]])

def change_data_type(data_set: np.array, data_type: np.dtype):  # добавь два аргумента для функции согласно условию
    return  data_set.astype(data_type)

temp_data =  change_data_type(temp_data, np.float64)
humid_data =  change_data_type(humid_data, np.float64)

print(f'Новый тип данных temp_data: {temp_data.dtype}')
print(f'Новый тип данных humid_data: {humid_data.dtype}')

Новый тип данных temp_data: float64
Новый тип данных humid_data: float64


In [23]:
arr = np.array([1, 'a', True, (2, 3), [4, 5]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (5,) + inhomogeneous part.

В NumPy, тип данных object представляет собой общий и гибкий тип, который может хранить объекты произвольного типа. Когда массив имеет тип данных object, это означает, что элементы массива могут быть любого типа данных, и каждый элемент массива фактически является объектом Python.

In [ ]:
arr = np.array([1, 'a', True, (2, 3), [4, 5]], dtype=object)
arr

## 1.5 Арифметические операции с массивами
<img src="https://ucarecdn.com/f1a8b477-8350-4933-808f-d7c18ab5b2bc/" width=1300>.
<img src="https://ucarecdn.com/1babf19f-aa71-4730-b7dd-9bfe173b4e91/" width=700>.
**Где @ - краткая форма записи матричного умножения (np.matmul)**

In [ ]:
print(a)
print(b)

In [ ]:
a + b

In [ ]:
a * b

In [ ]:
5 * b

In [ ]:
b_copy = b * 10
b + b_copy

In [ ]:
print(b @ b_copy)

In [ ]:
print(b * b_copy)

In [ ]:
print(a)
print(a * 5)

In [ ]:
b_copy = b[1: , 1:] # сделали 3x3
print(b_copy)
print(a + b_copy) # построчное сложение

In [ ]:
print(a + a*-1)

In [ ]:
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

arr1 / 4

In [ ]:
arr1 ** 2

In [ ]:
np.where(arr1 < 5, a , a*1000) # if statement, YES cond, NO cond

In [ ]:
matrix_a = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

vec_b = np.array([10,20,30]).reshape(3,1) # создайте вектор-столбец


print(matrix_a*vec_b)

## 1.6 Индексы и срезы

1.Slicing (cлайсинг/срез) в NumPy работает аналогично срезу в стандартном Python, но с добавлением некоторых особенностей для работы с многомерными массивами. Основные параметры среза в NumPy:

arr[start:stop:step]

    start: Начальный индекс среза. Элемент с этим индексом включается в срез.
    stop: Конечный индекс среза. Элемент с этим индексом не включается в срез.
    step: Шаг (или интервал) между выбранными элементами. Если не указан, используется шаг 1.

Некоторые важные замечания:

    Если start не указан, используется начало массива (индекс 0).
    Если stop не указан, используется конец массива (последний элемент).
    Если step не указан, используется шаг 1.
    Все эти параметры могут быть отрицательными, что означает выбор элементов в обратном порядке.
    В случае отрицательного step и отсутствия start и stop, массив будет выведен в обратном порядке.
<img src="https://ucarecdn.com/d82e7acf-1719-4d9b-a7c6-60d43de4c4f4/" width=1200>


In [ ]:
a = np.array([1,2,3,4,5,6,7])
print(a[4:123]) # OUT OF RANGE WONT GIVE YOU AN ERROR!

<img src="https://ucarecdn.com/b175cafe-a492-42c9-b3ae-c02f342a0981/" width=900>.
<img src="https://ucarecdn.com/d6258be9-27f9-4b9a-983a-6f2c3719c916/" width=900>.

In [ ]:
b

In [ ]:
b[1:2]

In [ ]:
b[1:2 , 1:3]

In [ ]:
b[: , 1:3]

In [ ]:
b[: , 0]

 <img src="https://ucarecdn.com/d15c0cbd-de5a-46ce-81fc-17edf40b9d13/" width=700>.

В NumPy различие между ```[:, :, 1] и [:, :, 1:2]``` заключается в форме итогового массива (слайса).

```[:, :, 1]```: Этот срез возвращает одномерный массив, выбирая второй столбец для каждой строки в каждой матрице. Результат - одномерный массив с элементами из второго столбца для каждой строки

Результат 
```
[:, :, 1:2]:
[[[ 2]
  [ 5]
  [ 8]]

 [[11]
  [14]
  [17]]

 [[20]
  [23]
  [26]]]
```
```[:, :, 1:2]```: Этот срез возвращает двумерный массив, выбирая второй столбец в виде двумерного среза. Результат - двумерный массив с элементами из второго столбца для каждой строки, но он сохраняет второй столбец как отдельное измерение. Размерность будет (3, 3, 1).
Результат ```[:, :, 1]```:
```
[[ 2  5  8]
 [11 14 17]
 [20 23 26]]
```

## 1.7 Основы Boolean Indexing:

Индексация по булевым значениям в Numpy — это механизм выбора элементов из массива на основе булевых условий. Это позволяет создавать условные выражения для фильтрации данных.

Можно создать булев массив такой же формы, что и исходный массив, применяя условные операции к элементам.
<img src="https://ucarecdn.com/9abcc990-3872-430a-8923-a91cc57db1c6/" width=800>

In [ ]:
print(b)
b_even = ((b+1)%2) # все четные элементы внутри b
# not(b%2) или !(b%2) не сработает!
# НО! (b%2==0) заработает
print(b_even)

Булев массив может быть использован как индекс для выбора элементов из массива, соответствующих True значениям в булевом массиве.

In [ ]:
print(b[ b > 5 ]) # Возвращает строку

Можно комбинировать несколько условий с использованием операторов ```&``` (и), ```|``` (или), ```~``` (не).

Затем этот булев массив может быть использован для выбора соответствующих элементов из исходного массива или замены значений.

***Не заработает внутри ```arr[ arr > 2 & arr < 6 ]``` , используйте скобки ```arr[(arr > 2) & (arr < 6)]```***

In [ ]:
comb_cond = (b % 2 ==0) & (b < 10) # b % 2 без указания остатка (==) не заработает
print(b[comb_cond])

Функция ```np.any``` используется для проверки, есть ли хотя бы один элемент в массиве, который оценивается как True.
```numpy.any(a, axis=None)```
```a```: Исходный массив.
```axis```: Опциональный параметр, определяющий по какой оси выполняется проверка. Если ```None``` (по умолчанию), то проверка выполняется по всем элементам массива.

In [ ]:
np.any(b < 0) # провекрка каждого элемента

In [ ]:
print(np.any(b > 10, axis=1)) # только в 2ой и 3ей строках есть элемент больше 10
print(b)

In [ ]:
print(np.all(b < 14, axis=0)) # только в первом столбце все элементы меньше 14
print(b)

<img src="https://ucarecdn.com/5e9e6486-78bf-4b95-81f1-4f423385651f/">.
<img src="https://ucarecdn.com/86098fbc-585a-4154-8d50-37742b8f4d03/">

In [ ]:
print(b)

In [ ]:
b_copy = np.array(b, copy=True)
b_copy[ 1:3 , 1:3]  = -1
print(b_copy)

In [ ]:
b_copy = np.array(b, copy=True)
b_copy[ b_copy[ : , 1] > 6, 1] = -1000
print(b_copy)

Если есть 2 массива - один с условием, втрой со значениями, то можно использовать ```np.where( условие , если да , в каком массиве менять )```

In [ ]:
index_arr = np.array([1,0,1,0,1,1,0])
a = np.array([1, 2, 3, 4, 5, 6, 7])
print(a)
print(np.where(index_arr == True, -1 , a))
print(a [index_arr == False])

*Задача*: Представим, у вас есть массив чисел, и вы хотите проверить, содержит ли он хотя бы одно положительное число и все ли элементы отрицательны. Необходимо проверить это с помощью функции check_array.

In [ ]:
# put your python code here
import numpy as np

def check_array(arr):
    has_positive =  np.any(arr > 0)
    all_negative =  np.all(arr < 0)

    return  has_positive , all_negative# функция должна возвращать два булева значения 

array2 = np.array([-2, -4, -6, -8, -1])
result = check_array(array2)

print(f"В массиве есть хотя бы одно положительное число: {result[0]}")
print(f"Все элементы массива отрицательны: {result[1]}")

Задача: Предположим, у вас есть набор данных о продажах товаров, представленный в виде двумерного массива sales_data_array. Каждая строка представляет собой информацию о продажах для конкретного товара, а столбцы содержат следующую информацию: номер товара, количество проданных единиц, и доход от продаж.

Ваша задача - проверить следующие условия:

>Есть ли хотя бы одна запись с нулевыми продажами (количество проданных единиц равно 0)?
>Все ли товары имеют положительный доход от продаж?


In [ ]:
# put your python code here
import numpy as np

sales_data_array = np.array([[1, 10, 100],
                             [2, 5, 50],
                             [3, 0, 0],
                             [4, 8, 80]])

def analyze_sales_data(sales_data):
    has_zero_sales =  np.any(sales_data[ : , 1] <= 0)
    all_positive_income = np.all(sales_data[ : , 2] > 0)

    return  has_zero_sales, all_positive_income

result =  analyze_sales_data(sales_data_array)# проверь массив sales_data_array с помощью функции analyze_sales_data

print(f"Есть ли товары с нулевыми продажами: {result[0]}")  # первое булево значение согласно условию
print(f"Все ли товары имеют положительный доход: {result[1]}")  # второе булево значение согласно условию

Задача: Дан массив data размером 5 x 5, заполненный случайными целыми числами от 0 до 9. Замените все четные числа в массиве на 0, а все нечетные на 1. Используйте булеву индексацию для создания масок, которые соответствуют этим условиям, и примените их к массиву data.  

``` 
Sample Output:

[[0 0 0 1 1]
 [0 0 1 1 0]
 [1 1 1 0 0]
 [1 1 0 0 0]
 [1 0 1 0 1]]
```

In [ ]:
# put your python code here
import numpy as np

data = np.array([[6, 4, 8, 7, 9],
                 [0, 0, 1, 7, 2],
                 [5, 7, 9, 0, 4],
                 [5, 1, 2, 8, 6],
                 [9, 8, 3, 0, 3]])

even_mask =  data [ data %2 == 0 ] # Одномерный массив из ЭЛЕМЕНТОВ 
odd_mask = data %2 == 1 # двумерная булевая матрица
print(even_mask)
print(odd_mask)

data = np.where(data % 2 == 0 , 0 , data) # Меняем элементы без Маски (ДВУМЕРНЫЙ БУЛЕВОЙ МАССИВ)
data[odd_mask] = 1 # Используем маску

data

Задача: Дан массив data размером 6 x 6, заполненный случайными целыми числами от 0 до 9. Найдите среднее арифметическое всех элементов, которые находятся на главной диагонали массива. Используйте булеву индексацию для создания маски, которая соответствует этому условию, и примените ее к массиву data

In [ ]:
# put your python code here
import numpy as np

data = np.array([[8, 3, 9, 1, 9, 0],
                 [5, 4, 2, 7, 4, 2],
                 [0, 8, 7, 4, 3, 9],
                 [0, 9, 7, 1, 0, 1],
                 [7, 1, 0, 3, 9, 3],
                 [5, 8, 0, 4, 0, 6]])

mask = np.eye(np.shape(data)[0],dtype=bool)

mean = np.mean(data[mask])

print(f'Среднее арифметическое элементов на диагоналях: {mean:.2f}')

Задача: Попробуем с настоящими данными. Дан массив data, содержащий информацию о студентах: имя, возраст, пол, курс и средний балл. Найдите имена, средние баллы и другую информацию студентов, которые старше 20 лет, женского пола и учатся на третьем курсе. Используйте булеву индексацию для создания маски, которая соответствует этому условию, и примените ее к массиву data.  

In [ ]:
# put your python code here
import numpy as np

data = np.array([
    ['Анна', 19, 'F', 1, 4.5],
    ['Борис', 21, 'M', 2, 3.7],
    ['Вера', 21, 'F', 3, 4.8],
    ['Глеб', 22, 'M', 4, 3.9],
    ['Дарья', 18, 'F', 1, 4.2],
    ['Егор', 23, 'M', 3, 4.1],
    ['Жанна', 21, 'F', 2, 4.6],
    ['Захар', 19, 'M', 1, 4.0]
])

mask = (data[: , 1].astype(int) > 20) & (data[ : , 2] == 'F') & (data[ : , 3].astype(int) == 3)

result = data[mask]

print(result)

## 1.8 Транспонирование Массивов
Транспонирование — это операции, которые позволяют изменять форму (или структуру) массивов в языке программирования Python, особенно при использовании библиотеки NumPy.

In [ ]:
c = np.array([[1,2,3],[4,5,6]])
print(c)

In [ ]:
# np.ndarray.T
print(c.T)

Метод dot используется для вычисления скалярного произведения векторов или матричного умножения (если массивы являются двумерными, то выполняется матричное умножение, однако в этом случае предпочтительно использовать matmul или @)
<img src="https://ucarecdn.com/41d77d70-17a3-4083-8584-ab1fe074430a/">

In [ ]:
print(c.T)
print(b[:-1 , :-1])

In [ ]:
print(b[:-1 , :-1] @ c.T) # матричное умножение "@" shape совпадает строка:столбец
print(np.multiply(b[:-1 , :-2] , c.T)) # Поэлементное умножение "*" shape совпадает 1:1

In [ ]:
np.matmul(b[:-1 , :-1] , c.T) # np.dot лучше НЕ использовать!

In [ ]:
b[:-1 , :-1].dot(c.T)

np.reshape() 
<img src="https://ucarecdn.com/0698a894-c885-4d51-9375-02560dc732fd/" width=800>

In [ ]:
print(b)

In [ ]:
print(b.reshape(8,2))

In [ ]:
b.reshape(16) # 16 строк и 1 столбец

In [ ]:
b.reshape(1,16) # 1 строка и 16 столбцов

In [ ]:
print(c.T)

Метод swapaxes используется для обмена осями массива, меняя местами указанные оси.
<img src="https://ucarecdn.com/c88c08c2-2e9e-407d-835d-37a053fba321/" width=700>

In [ ]:
print(c)

In [ ]:
print(np.swapaxes(c, 0, 1))

In [ ]:
print(b)
print('')
print(np.swapaxes(b, 1, 0)) # аналогично транспонированию!

In [ ]:
b = np.reshape(np.arange(16), (4,4)) # создание двумерного массива
print(b)

In [ ]:
A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

A = A[ :2 , :2 ].T
A

In [ ]:
# Транспонировать только те строки, у которых первый элемент больше 3
A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16],
              [17, 18, 19, 20]])
mask = A[ : , 0] > 3
A[mask] =  A[mask].T
print(A)

# 2. Универсальные функции

## 2.1 Унарные универсальные функции

Унарные универсальные функции в NumPy представляют собой функции, которые выполняют операции над отдельными элементами массивов. Они называются "унарными", потому что они оперируют только над одним операндом. Универсальные функции (universal functions, или ufuncs) в NumPy представляют собой векторизованные функции, что означает, что они могут применяться к массивам любой формы и размера, выполняя операцию над каждым элементом массива.

Эти функции обеспечивают быстрый и эффективный способ применения математических операций к элементам массива без необходимости использования явных циклов.

### Список функций
    1. abs/fabs - Вычисляет абсолютное значение элементов массива
    2. sqrt - Вычисляет квадратный корень из каждого элемента массива.
    3. square - Возводит каждый элемент массива в квадрат.
    4. exp - Вычисляет экспоненту для каждого элемента массива (e^x).
    5. log, log10, log2, log1p - Вычисляют натуральный логарифм (log_e), логарифм по основанию 10, логарифм по основанию 2, и log(1 + x), соответственно.
    6. sign-  Определяет знак каждого элемента: 1 (положительное), 0 (ноль), или –1 (отрицательное).
    7. ceil - Вычисляет наименьшее целое число, не меньшее каждого элемента массива (округление по верхней границе)
    8. floor - Вычисляет наибольшее целое число, не большее каждого элемента массива (округление по нижней границе).
    9. round - ычисляет наибольшее целое число, не большее каждого элемента массива (округление по арифметическому правилу).
    10. rint - Округляет элементы массива до ближайшего целого числа, сохраняя тип данных
    11. modf - Возвращает дробную и целую части каждого элемента массива в двух отдельных массивах
    12. isin - Используется для проверки наличия элементов одного массива в другом. Она возвращает булев массив той же формы, что и входные массивы, указывающий, где элементы из второго массива присутствуют во первом массиве.
    13. isnan - Возвращает булев массив, показывающий, является ли каждый элемент NaN (Not a Number)
    14. isfinite, isinf - Возвращают булев массив, указывающий, является ли каждый элемент конечным числом или бесконечностью
<img src="https://ucarecdn.com/054de241-ea67-481d-885c-0c468e243dbc/">
    

In [ ]:
np.square(b, dtype=float)

In [ ]:
# put your python code here
import numpy as np

array = np.array([2.5, -3.7, 4.2])

fractional_part, integer_part =  np.modf(array)

print(f'Дробная часть: {fractional_part}')
print(f'Целая часть: {integer_part}')

## 2.2.1 Бинарные функции (Binary Universal Functions (ufuncs)) в NumPy представляют собой функции, которые выполняют операции над парами элементов входных массивов:

    1. add "+"- Выполняет поэлементное сложение двух массивов
    2. subtract "-"- Выполняет поэлементное вычитание второго массива из первого
    3. multiply "*"- Выполняет поэлементное умножение двух массивов.
    4. divide "/" / floor_divide - divide(возврщает FLOAT) выполняет поэлементное деление первого массива на второй. floor_divide также округляет результат вниз, возвращая только целую часть (INT).
    5. power "**" - Возводит элементы первого массива в степени, указанные во втором массиве.
    6. maximum / fmax - maximum возвращает поэлементный максимум двух массивов. fmax также возвращает максимум, игнорируя значения NaN. **np.max не заработает**
    7. minimum / fmin - minimum возвращает поэлементный минимум двух массивов. fmin также возвращает минимум, игнорируя значения NaN. **np.min не заработает**
    8. mod "%"- Вычисляет остаток от деления элементов первого массива на соответствующие элементы второго массива (либо заданнаго числа). 
    9. copysign - Копирует знак значения из второго массива в значения первого массива.
    10. grater - Сравнивает каждый элемент двух массивов поэлементно и возвращает булев массив той же формы, где каждый элемент равен True, если соответствующий элемент в x больше соответствующего элемента в y, и False в противном случае.
    11. grater_equal - Сравнивает каждый элемент двух массивов поэлементно и возвращает булев массив, где каждый элемент равен True, если соответствующий элемент в x больше или равен соответствующему элементу в y, и False в противном случае.
    12. less - Сравнивает каждый элемент двух массивов поэлементно и возвращает булев массив, где каждый элемент равен True, если соответствующий элемент в x меньше соответствующего элемента в y, и False в противном случае.
    13. less_equal -  Сравнивает каждый элемент двух массивов поэлементно и возвращает булев массив, где каждый элемент равен True, если соответствующий элемент в x меньше или равен соответствующему элементу в y, и False в противном случае.
    14. equal - Сравнивает каждый элемент двух массивов поэлементно и возвращает булев массив, где каждый элемент равен True, если соответствующий элемент в x равен соответствующему элементу в y, и False в противном случае.
    15. np.not_equal - Сравнивает каждый элемент двух массивов поэлементно и возвращает булев массив, где каждый элемент равен True, если соответствующий элемент в x не равен соответствующему элементу в y, и False в противном случае.
    16. np.in1d - проверяет какие элементы содержаться в обоих массивах

In [ ]:
print(b ** 2)

## 2.2.2 Логические операции:
    1. np.logical_and - Выполняет поэлементную логическую операцию И между элементами двух массивов и возвращает булев массив, где каждый элемент равен True, если оба соответствующих элемента входных массивов равны True, и False в противном случае.
    2. np.logical_or - Выполняет поэлементную логическую операцию ИЛИ между элементами двух массивов и возвращает булев массив, где каждый элемент равен True, если хотя бы один из соответствующих элементов входных массивов равен True, и False в противном случае.
    3. np.logical_xor -  Выполняет поэлементную логическую операцию "исключающее ИЛИ" между элементами двух массивов и возвращает булев массив, где каждый элемент равен True, если ровно один из соответствующих элементов входных массивов равен True, и False в противном случае.
    4. np.logical_not - выполняет поэлементную логическую операцию НЕ (logical NOT) для массивов и возвращает булев массив, где каждый элемент равен True, если соответствующий элемент входного массива равен False, и наоборот.

In [ ]:
c = (np.arange(16).reshape((4,4)) % 3 == 0)
print(c)
print(b%2==0)
np.logical_and(b%2==0,c)

Задача: У вас есть массив чисел secret_codes, представляющих собой последовательность некоторых секретных кодов. К сожалению, не все коды были переданы вам, а только часть provided_codes. Вам нужно определить, какие коды вам не предоставили.

In [ ]:

secret_codes = np.array([15, 23, 7, 42, 18, 10, 7, 29])
provided_codes = np.array([23, 7, 18, 7])

missing = np.isin(secret_codes, provided_codes)
missing_codes = secret_codes[~missing]
missing_codes



Задача: Есть два массива, celsius_temps представляющий температуру в градусах Цельсия и days представляющий дни в которые эта температура была зарегистрирована. Определите, в какие дни температура в Фаренгейтах была выше 90, а в Цельсиях не ниже 30.

Формула температуры в Фаренгейтах: 
```F =  C * 9 / 5 + 32```
где:
    F - температура в градусах Фаренгейта,
    C - температура в градусах Цельсия.
    
---

Sample Input:

---
Sample Output:
Температура выше 90 по Фаренгейту: ['четверг']
Температура не ниже 30 Цельсия: ['вторник' 'четверг' 'пятница']



In [ ]:
# put your python code here
import numpy as np

celsius_temps = np.array([25, 32, 28, 35, 30])
days = np.array(['понедельник', 'вторник', 'среда', 'четверг', 'пятница'])

fahrenheit_temps =  (celsius_temps * (9/5)) + 32
print(fahrenheit_temps)

hot_days_fahrenheit_temps =  days[ fahrenheit_temps > 90 ]
hot_days_celsius_temps =  days[ celsius_temps >= 30 ]

print(f'Температура выше 90 по Фаренгейту: {hot_days_fahrenheit_temps}')
print(f'Температура не ниже 30 Цельсия: {hot_days_celsius_temps}')

Задача: Есть массив, представляющий возрастающую последовательность чисел. Определите, какие числа удовлетворяют критериям: больше 10 и не больше 30, и не равны 15.

In [ ]:
numbers = np.array([5, 12, 15, 20, 25, 30, 35])

condition1 = ( numbers > 10 ) & ( numbers <= 30 )
condition2 =  numbers != 15

filtered_numbers =  numbers [ condition1 & condition2 ]

print(f'Числа, удовлетворяющие условиям: {filtered_numbers}')

# 3. Программирование на основе массивов

## 3.1 Запись логических условий в виде операций с массивами 
Запись логических условий в виде операций с массивами — это способ применения логических условий к элементам массивов в NumPy. Это позволяет создавать новые массивы на основе значений других массивов, используя функцию np.where. 

```np.where``` — это функция библиотеки NumPy в Python, предназначенная для выполнения условного элементарного поэлементного выбора значений из двух массивов в зависимости от заданного условия. Она имеет несколько форм синтаксиса, основные из которых выглядят следующим образом:

```numpy.where(condition[x, y])```
    - condition: Логическое выражение или массив булевых значений. Если condition равно True, то соответствующее значение из x выбирается, в противном случае - из y.
    - x: Значение или массив, используемый при условии True.
    - y: Значение или массив, используемый при условии False.
    
<img src="https://ucarecdn.com/2c318b85-503b-464b-b8ee-aa96a07d7cc6/" width=600>

*Варианты использования:*
    1. Простой выбор между двумя значениями
    ```y = np.where(x > 3, 'больше трех', 'три и меньше')```
    ```# ['три и меньше' 'три и меньше' 'три и меньше' 'больше трех' 'больше трех']```
    2. Замена значений в массиве
    ```y = np.where(x % 2 == 0, 'четное', 'нечетное')
    # ['нечетное' 'четное' 'нечетное' 'четное' 'нечетное']```
    3. Использование без явного указания ```y```
    ```out = np.where(x > 2)
    print(out)
    # (array([2, 3, 4]),)```

In [ ]:
print(b)
print(np.where( (b < 10) & (b % 2 == 1) , -1 ,b))

In [ ]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
z = np.where(x > 2, x, y)
z

Выберите значения, которые нечетные и больше 3 или четные и меньше 0. Остальные значения замените на ноль.

In [ ]:
selected_values = np.where ( ( (b > 3) & (b % 2==1) ) | ( (b < 0) & (b %2==0) ) , b , 0 )

## 3.2 Математические и статистические операции с массивами 

Математические и статистические операции с массивами в библиотеке NumPy включают в себя различные функции, позволяющие проводить вычисления с элементами массивов. Эти операции обеспечивают мощные инструменты для анализа данных, научных вычислений и многих других приложений. Вот некоторые из ключевых операций:

*Список основных функций*:
    1. ```sum``` - Вычисляет сумму элементов массива.
    2. ```mean``` - Вычисляет среднее значение элементов массива.
    3. ```median```  - Метод numpy.median() используется для вычисления медианы значений в массиве. Медиана - это значение, которое делит упорядоченный массив пополам, то есть половина значений меньше медианы, а другая половина больше.
    4. ```std``` - Вычисляет стандартное отклонение элементов массива.
    5. ```var``` - Вычисляет дисперсию элементов массива. (variance)
    6. ```min/max``` - Возвращает минимальное/максимальное значение в массиве
    7. ```argmin/argmax``` - Возвращает индекс минимального/максимального значения в массиве.
    8. ```cumsum``` - Возвращает кумулятивные суммы элементов массива. Для массива [a, b, c, d, ...], кумулятивная сумма будет [a, a+b, a+b+c, a+b+c+d, ...].
    9. ```cumprod``` -  Возвращает кумулятивные произведения элементов массива.
Для массива [a, b, c, d, ...], кумулятивное произведение будет [a, a*b, a*b*c, a*b*c*d, ...].
    10. ```np.ptp``` - Peak-to-Peak, ptp возвращает размах (peak-to-peak) значений в массиве, то есть разницу между максимальным и минимальным значениями.
    11. ```np.diff``` - diff вычисляет разности между соседними элементами массива. Этот метод особенно полезен при анализе изменений во временных рядах данных.
    12. ```np.bincount(arr)``` - это метод библиотеки NumPy, предназначенный для подсчета частоты встречаемости каждого неотрицательного целого числа в массиве. Массив может содержать только неотрицательные целые числа. 
    ```Массив данных: [1 2 2 3 4 4 4]```
    ```Количество вхождений каждого значения: [0 1 2 1 3]```

In [ ]:
arr = np.array([22, 13, 45, 7, 19])

result1 =  np.argmin(arr)
result2 =  arr.argmax()
result1 , result2

Задача: Представим, что у вас есть данные о ежедневных изменениях стоимости акций компании. Используйте методы для анализа финансовых показателей. Найдите изменение цен за каждый день, а также дни с минимальным и максимальным изменением. (Внимание: Не забудьте что когда вы ищите изменение в ценах, то кол-во значений уменьшается на 1, т.к. первое значение не с чем сравнивать.)

In [ ]:
# put your python code here
import numpy as np

stock_prices = np.array([50, 55, 60, 52, 48, 65, 70])
days = np.array(['понедельник', 'вторник', 'среда', 'четверг', 'пятница', 'суббота', 'воскресенье'])

daily_returns =  np.diff(stock_prices)
best_day =  days [ np.argmax(daily_returns) + 1]
worst_day =  days [ np.argmin(daily_returns) + 1]


print(f"Изменения цен за день: {daily_returns}")
print(f"Лучший день: {best_day}")
print(f"Худший день: {worst_day}")

Задача: Вам предоставлен массив доходов отдельных инвесторов за год. Необходимо рассчитать медиану доходов и выполнить дополнительные шаги:

    Найти медиану доходов.
    Определить, сколько инвесторов заработали выше медианного значения, а сколько ниже.
    Найти разброс доходов для инвесторов, заработавших выше медианы.


In [ ]:
# Заданные данные (доходы инвесторов в тысячах долларов)
income_data = np.array([40, 55, 60, 75, 80, 85, 90, 100, 120, 150])

median_income =  np.median(income_data)

above_median =  income_data[income_data > median_income]
below_median =  income_data[income_data < median_income]

#print(above_median)
income_range_above_median =  np.ptp(above_median)

print("Медиана доходов:", median_income)
print("Инвесторы, заработавшие выше медианы:", above_median)
print("Инвесторы, заработавшие ниже медианы:", below_median)
print("Разброс доходов для инвесторов, заработавших выше медианы:", income_range_above_median)

Задача: Найдите среднюю стоимость акций каждой компании за все дни. Затем определите компанию с максимальной волатильностью (наибольшим размахом цен). И под конец, найдите день с наибольшим общим изменением в стоимости акций всех компаний.

Средняя стоимость акций каждой компании: [120.71 121.43 120.86]
Индекс самой волатильной компании: 2
Индекс дня с наибольшим изменением в стоимости акций: 3



In [ ]:
# put your python code here
import numpy as np

# Цены акций для 3 компаний(каждый столбец - отдельная компания)
stock_prices = np.array([
    [110, 112, 108],
    [115, 118, 120],
    [108, 110, 105],
    [122, 121, 124],
    [128, 130, 125],
    [133, 132, 134],
    [129, 127, 130]
])

average_prices = np.round(np.mean(stock_prices, axis=0), 2)# Средняя стоимость акций каждой компании за все дни (ответ округлите до 2-х знаков после запятой)

volatility = np.ptp(stock_prices, axis=0)
most_volatile_company = np.argmax(volatility)
# 
#x = np.array([i for i in np.split(stock_prices,3,axis=1)]).reshape((3,1,7))
#y = np.diff(x).reshape((3,6,1))[: , : , 0]
#z = np.array([ np.sum(y[ : , i]) for i in range(len(y[0])) ])
total_daily_change =  np.sum(np.abs(np.diff(stock_prices, axis=0)), axis=1)

day_with_max_change = np.argmax(total_daily_change) + 1 # Индекс дня(строки) с наибольшим общим изменением в стоимости акций всех компаний.
# 
print("Средняя стоимость акций каждой компании:", average_prices)
print("Индекс самой волатильной компании:", most_volatile_company)
print("Индекс дня с наибольшим изменением в стоимости акций:", day_with_max_change)


Задача: Найдите средний возраст пациентов. Определите пациента с самым высоким уровнем холестерина и самым низким давлением.

Средний возраст пациентов: 36.7
Пациент с самым высоким уровнем холестерина: [ 45 220 130]
Пациент с самым низким давлением: [ 35 190 110]

In [ ]:
# put your python code here
import numpy as np

# Заданные данные (1-й столбец: возраст, 2-й столбец: уровень холестерина, 3-й столбец: давление)
medical_data = np.array([
    [30, 200, 120],
    [45, 220, 130],
    [35, 190, 110]
])

average_age = np.round(np.mean(medical_data[: , 0]),1)
max_cholesterol_patient = np.argmax(medical_data[: , 1])# Индекс пациента с самым высоким уровнем холестерина
min_pressure_patient =  np.argmin(medical_data[: , 2])# Индекс пациента с самым низким давлением

print(f"Средний возраст пациентов: {average_age}")
print("Пациент с самым высоким уровнем холестерина:", medical_data[max_cholesterol_patient]) # Показатели пациента с самым высоким уровнем холестерина
print("Пациент с самым низким давлением:", medical_data[min_pressure_patient]) # Показатели пациента с самым низким давлением

## 3.3 Сортировка и другие операции

```np.sort(a, axis=-1, kind=None, order=None)```  -  выполняет сортировку элементов массива.
 - a: Исходный массив, который нужно отсортировать.
 - axis: Опциональный параметр, указывающий ось, по которой нужно провести сортировку. По умолчанию -1, что означает сортировку по последней оси.
 - kind: Опциональный параметр, определяющий алгоритм сортировки. Может принимать значения 'quicksort', 'mergesort', 'heapsort' или None. По умолчанию используется 'quicksort'.
 - order: Опциональный параметр, применяется при сортировке структурированных массивов. Может содержать названия полей и направления сортировки для каждого поля.
<img src="https://ucarecdn.com/26d962df-de4e-4682-9d7f-3dc8014de6b4/">

```np.unique(ar, return_index=False, return_inverse=False, return_counts=False, axis=None)``` - это функция, которая возвращает уникальные элементы массива. 

- return_index: Если True, то также возвращает массив индексов первого вхождения уникальных элементов.
- return_inverse: Если True, то также возвращает массив, который при использовании как индекс восстанавливает исходный массив.
- return_counts: Если True, то также возвращает массив, содержащий количество вхождений каждого уникального элемента.
- axis: Опциональный параметр, указывающий ось, по которой нужно найти уникальные элементы. Если не указан, поиск производится по всему массиву.
<img src="https://ucarecdn.com/b83aabf6-7891-41bd-aee3-db4aaeb17315/">

```numpy.intersect1d(ar1, ar2, assume_unique=False, return_indices=False)``` - Возвращает отсортированный массив уникальных элементов, общих для двух входных массивов.
- assume_unique: Если True, то предполагает, что входные массивы уже уникальны, что ускоряет выполнение.
- return_indices: Если True, то также возвращает индексы элементов в каждом из входных массивов

```np.union1d(ar1, ar2)``` - Возвращает отсортированный массив уникальных элементов, объединенных из двух входных массивов.
<img src="https://ucarecdn.com/a3cd125b-37f5-490c-bfc1-32793ebd211f/">

```np.in1d(ar1, ar2, assume_unique=False, invert=False)``` - Возвращает булев массив той же формы, что и ar1, указывающий, содержатся ли элементы ar1 в ar2.
 - assume_unique: Если True, то предполагает, что ar1 и ar2 уже уникальны.
 - invert: Если True, то инвертирует результат, то есть возвращает, содержатся ли элементы ar1 не в ar2.

<img src="https://ucarecdn.com/229dc3ff-416f-4bae-878e-ac3e7ff3e1f5/">

```np.setdiff1d(ar1, ar2, assume_unique=False)``` - Возвращает уникальные элементы, которые есть в ar1, но отсутствуют в ar2.
```np.setxor1d(ar1, ar2, assume_unique=False)``` - Возвращает уникальные элементы, которые есть в одном из массивов, но отсутствуют в обоих

```np.delete(arr, obj, axis=None)``` - это функция библиотеки NumPy, которая используется для удаления элементов из массива. Она может использоваться для удаления как отдельных элементов, так и целых строк или столбцов в многомерных массивах. 

- arr: Одномерный массив неотрицательных целых чисел. Обязательный параметр.
- arr: Исходный массив.
- obj: Объект, который нужно удалить. Это может быть индекс, срез или последовательность индексов/срезов. Функция возвращает новый массив с удаленными элементами. Исходный массив не изменяется.
- axis: Опциональный параметр, указывающий ось, по которой нужно удалить элементы. Если axis не указан, функция работает с плоским массивом.

<img src="https://ucarecdn.com/1ee00444-4053-448c-a605-d1abe0a713be/" width=600>.

<img src="https://ucarecdn.com/71b5b026-b397-434b-b989-35b4124d7017/">


##  3.4 Дополнительно: Генерация псевдослучайных чисел в Numpy

В NumPy генерация псевдослучайных чисел выполняется с использованием модуля numpy.random. Этот модуль полезен в различных задачах, таких как создание случайных массивов, симуляция случайных процессов и другие приложения, где требуется использование случайности. Вот несколько основных функций для генерации псевдослучайных чисел в NumPy:

<img src="3.4.png">.