In [56]:
import numpy as np

## 1.2 Создание массива

<img src="https://ucarecdn.com/09b174e8-e8b2-4c10-990c-570057daf8c8/" alt="drawing" width="400"/>.
<img src="https://ucarecdn.com/a659ae99-e9f5-4523-be7d-eae05bfbf195/" alt="drawing" width="600"/>.
<img src="https://ucarecdn.com/06e69802-f635-45dc-a3a9-95337ce1a6b8/" width="800"/>.
<img src="https://ucarecdn.com/1450cdcd-22ac-40e0-86ef-05ff27bf8510/" width="400"/>.

In [57]:
a = np.array([1,2,3])
b = np.array(([1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]), dtype=np.float64)
c = np.zeros((3,5))
d = np.ones((1,5))
print(a)
print(b)
print(c)
print(d)

[1 2 3]
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]]


In [58]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
np.arange(1,5)

array([1, 2, 3, 4])

In [60]:
print(np.arange(0,1 + 0.1,0.1))


[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [61]:
print(np.linspace(0,1)) # num (необязательный): Количество элементов в массиве. По умолчанию 50.

[0.         0.02040816 0.04081633 0.06122449 0.08163265 0.10204082
 0.12244898 0.14285714 0.16326531 0.18367347 0.20408163 0.2244898
 0.24489796 0.26530612 0.28571429 0.30612245 0.32653061 0.34693878
 0.36734694 0.3877551  0.40816327 0.42857143 0.44897959 0.46938776
 0.48979592 0.51020408 0.53061224 0.55102041 0.57142857 0.59183673
 0.6122449  0.63265306 0.65306122 0.67346939 0.69387755 0.71428571
 0.73469388 0.75510204 0.7755102  0.79591837 0.81632653 0.83673469
 0.85714286 0.87755102 0.89795918 0.91836735 0.93877551 0.95918367
 0.97959184 1.        ]


In [62]:
np.linspace(0,5,9)

array([0.   , 0.625, 1.25 , 1.875, 2.5  , 3.125, 3.75 , 4.375, 5.   ])

In [63]:
np.full((3,3),7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [64]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## 1.3 Создание массива часть 2

In [65]:
np.ones([3,2])

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

<img src="https://ucarecdn.com/c6cf7ceb-9a35-4001-9410-2259da43d47c/" width="600"/>.
<img src="https://ucarecdn.com/c544842a-29cd-48d8-b4a6-1d139228f5d3/" width="300"/>.

In [66]:
print(b)
print(np.ndim(b))
print(np.shape(b))
print(np.size(b))

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]
2
(4, 4)
16


In [67]:
print(np.eye(5,3)) # Еденичная матрица
print(np.eye(3,3)) # аналогично identity
print(np.identity(3)) # создает квадратную матрицу с единицами на главной диагонали и нулями в остальных местах.
# В отличие от numpy.identity,  numpy.eye позволяет создавать матрицы с единичной диагональю 
# произвольной размерности и выполнять сдвиг этой диагонали относительно главной диагонали.
print('')
print(np.eye(5,k=2))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [68]:
np.random.rand( 3,3 )

array([[0.11370715, 0.92533356, 0.18117333],
       [0.10389123, 0.68297208, 0.48254231],
       [0.40239842, 0.22598218, 0.95691249]])

In [69]:
np.random.randint(10) # случайное число от 0 до 10 (целое)

4

In [70]:
print(np.random.randint(1,10, size=5))

[5 2 5 5 5]


In [71]:
print(np.random.randint(1,10, size=(3,3)))

[[6 9 7]
 [4 2 1]
 [2 4 7]]


In [72]:
small_arr = np.array([[1,2],[3,4]])
small_arr

array([[1, 2],
       [3, 4]])

In [73]:
print(np.tile(small_arr,reps=3))

[[1 2 1 2 1 2]
 [3 4 3 4 3 4]]


In [74]:
print(np.tile(small_arr,reps=(3,3)))

[[1 2 1 2 1 2]
 [3 4 3 4 3 4]
 [1 2 1 2 1 2]
 [3 4 3 4 3 4]
 [1 2 1 2 1 2]
 [3 4 3 4 3 4]]


## 1.4 Типы Данных

int(16-64), float(16-64), complex(64-128), bool, string, object (используется для хранения произвольных объектов Python в массивах NumPy)

In [75]:
print(b*0.2)
print(np.dtype(b[0][0]))
b.dtype

[[0.2 0.4 0.6 0.8]
 [1.  1.2 1.4 1.6]
 [1.8 2.  2.2 2.4]
 [2.6 2.8 3.  3.2]]
float64


dtype('float64')

In [76]:
# array.astype(dtype, order='K', casting='unsafe', subok=True, copy=True)
b_int = (b*0.2).astype(np.int64)
print(b_int)
b.dtype

[[0 0 0 0]
 [1 1 1 1]
 [1 2 2 2]
 [2 2 3 3]]


dtype('float64')

Задача: Предположим, у вас есть два датасета с данными о температуре и влажности. Каждый датасет представлен в виде двумерного массива, где строки представляют дни, а столбцы представляют конкретные моменты времени в течение дня. Тип данных - int. Но вам нужно изменить их на float.

In [77]:
# put your python code here
import numpy as np

# Датасет температуры (тип данных: int)
temp_data = np.array([[22, 25, 24, 23, 21],
                      [20, 18, 19, 22, 24]])

# Датасет влажности (тип данных: int)
humid_data = np.array([[45, 50, 48, 52, 47],
                       [45, 48, 50, 51, 53]])

def change_data_type(data_set: np.array, data_type: np.dtype):  # добавь два аргумента для функции согласно условию
    return  data_set.astype(data_type)

temp_data =  change_data_type(temp_data, np.float64)
humid_data =  change_data_type(humid_data, np.float64)

print(f'Новый тип данных temp_data: {temp_data.dtype}')
print(f'Новый тип данных humid_data: {humid_data.dtype}')

Новый тип данных temp_data: float64
Новый тип данных humid_data: float64


In [78]:
arr = np.array([1, 'a', True, (2, 3), [4, 5]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (5,) + inhomogeneous part.

В NumPy, тип данных object представляет собой общий и гибкий тип, который может хранить объекты произвольного типа. Когда массив имеет тип данных object, это означает, что элементы массива могут быть любого типа данных, и каждый элемент массива фактически является объектом Python.

In [79]:
arr = np.array([1, 'a', True, (2, 3), [4, 5]], dtype=object)
arr

array([1, 'a', True, (2, 3), list([4, 5])], dtype=object)

## 1.5 Арифметические операции с массивами
<img src="https://ucarecdn.com/f1a8b477-8350-4933-808f-d7c18ab5b2bc/" width=1300>.
<img src="https://ucarecdn.com/1babf19f-aa71-4730-b7dd-9bfe173b4e91/" width=700>.
**Где @ - краткая форма записи матричного умножения (np.matmul)**

In [80]:
print(a)
print(b)

[1 2 3]
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]


In [81]:
a + b

ValueError: operands could not be broadcast together with shapes (3,) (4,4) 

In [82]:
a * b

ValueError: operands could not be broadcast together with shapes (3,) (4,4) 

In [83]:
5 * b

array([[ 5., 10., 15., 20.],
       [25., 30., 35., 40.],
       [45., 50., 55., 60.],
       [65., 70., 75., 80.]])

In [84]:
b_copy = b * 10
b + b_copy

array([[ 11.,  22.,  33.,  44.],
       [ 55.,  66.,  77.,  88.],
       [ 99., 110., 121., 132.],
       [143., 154., 165., 176.]])

In [85]:
print(b @ b_copy)

[[ 900. 1000. 1100. 1200.]
 [2020. 2280. 2540. 2800.]
 [3140. 3560. 3980. 4400.]
 [4260. 4840. 5420. 6000.]]


In [86]:
print(b * b_copy)

[[  10.   40.   90.  160.]
 [ 250.  360.  490.  640.]
 [ 810. 1000. 1210. 1440.]
 [1690. 1960. 2250. 2560.]]


In [87]:
print(a)
print(a * 5)

[1 2 3]
[ 5 10 15]


In [88]:
b_copy = b[1: , 1:] # сделали 3x3
print(b_copy)
print(a + b_copy) # построчное сложение

[[ 6.  7.  8.]
 [10. 11. 12.]
 [14. 15. 16.]]
[[ 7.  9. 11.]
 [11. 13. 15.]
 [15. 17. 19.]]


In [89]:
print(a + a*-1)

[0 0 0]


In [96]:
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

arr1 / 4

array([[0.25, 0.5 , 0.75],
       [1.  , 1.25, 1.5 ],
       [1.75, 2.  , 2.25]])

In [97]:
arr1 ** 2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [99]:
np.where(arr1 < 5, a , a*1000) # if statement, YES cond, NO cond

array([[   1,    2,    3],
       [   1, 2000, 3000],
       [1000, 2000, 3000]])

In [107]:
matrix_a = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

vec_b = np.array([10,20,30]).reshape(3,1) # создайте вектор-столбец


print(matrix_a*vec_b)

[[ 10  20  30]
 [ 80 100 120]
 [210 240 270]]


## 1.6 Индексы и срезы