In [1]:
import numpy as np

<img src="https://ucarecdn.com/09b174e8-e8b2-4c10-990c-570057daf8c8/" alt="drawing" width="400"/>.
<img src="https://ucarecdn.com/a659ae99-e9f5-4523-be7d-eae05bfbf195/" alt="drawing" width="600"/>.
<img src="https://ucarecdn.com/06e69802-f635-45dc-a3a9-95337ce1a6b8/" width="800"/>.
<img src="https://ucarecdn.com/1450cdcd-22ac-40e0-86ef-05ff27bf8510/" width="400"/>.

In [2]:
a = np.array([1,2,3])
b = np.array(([1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]), dtype=np.float64)
c = np.zeros((3,5))
d = np.ones((1,5))
print(a)
print(b)
print(c)
print(d)

[1 2 3]
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]]


In [3]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.arange(1,5)

array([1, 2, 3, 4])

In [5]:
print(np.arange(0,1 + 0.1,0.1))


[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [6]:
print(np.linspace(0,1)) # num (необязательный): Количество элементов в массиве. По умолчанию 50.

[0.         0.02040816 0.04081633 0.06122449 0.08163265 0.10204082
 0.12244898 0.14285714 0.16326531 0.18367347 0.20408163 0.2244898
 0.24489796 0.26530612 0.28571429 0.30612245 0.32653061 0.34693878
 0.36734694 0.3877551  0.40816327 0.42857143 0.44897959 0.46938776
 0.48979592 0.51020408 0.53061224 0.55102041 0.57142857 0.59183673
 0.6122449  0.63265306 0.65306122 0.67346939 0.69387755 0.71428571
 0.73469388 0.75510204 0.7755102  0.79591837 0.81632653 0.83673469
 0.85714286 0.87755102 0.89795918 0.91836735 0.93877551 0.95918367
 0.97959184 1.        ]


In [7]:
np.linspace(0,5,9)

array([0.   , 0.625, 1.25 , 1.875, 2.5  , 3.125, 3.75 , 4.375, 5.   ])

In [13]:
np.full((3,3),7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [17]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [26]:
np.ones([3,2])

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

<img src="https://ucarecdn.com/c6cf7ceb-9a35-4001-9410-2259da43d47c/" width="600"/>.
<img src="https://ucarecdn.com/c544842a-29cd-48d8-b4a6-1d139228f5d3/" width="300"/>.

In [32]:
print(b)
print(np.ndim(b))
print(np.shape(b))
print(np.size(b))

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]
2
(4, 4)
16


In [59]:
print(np.eye(5,3)) # Еденичная матрица
print(np.eye(3,3)) # аналогично identity
print(np.identity(3)) # создает квадратную матрицу с единицами на главной диагонали и нулями в остальных местах.
# В отличие от numpy.identity,  numpy.eye позволяет создавать матрицы с единичной диагональю 
# произвольной размерности и выполнять сдвиг этой диагонали относительно главной диагонали.
print('')
print(np.eye(5,k=2))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [41]:
np.random.rand( 3,3 )

array([[0.04270485, 0.04381318, 0.19928386],
       [0.98112785, 0.89267725, 0.69903434],
       [0.90089882, 0.58305816, 0.14297169]])

In [45]:
np.random.randint(10) # случайное число от 0 до 10 (целое)

TypeError: Unsupported dtype dtype('float16') for randint

In [47]:
print(np.random.randint(1,10, size=5))

[7 1 9 9 1]


In [48]:
print(np.random.randint(1,10, size=(3,3)))

[[4 9 1]
 [2 7 4]
 [7 4 4]]


In [50]:
small_arr = np.array([[1,2],[3,4]])
small_arr

array([[1, 2],
       [3, 4]])

In [54]:
print(np.tile(small_arr,reps=3))

[[1 2 1 2 1 2]
 [3 4 3 4 3 4]]


In [55]:
print(np.tile(small_arr,reps=(3,3)))

[[1 2 1 2 1 2]
 [3 4 3 4 3 4]
 [1 2 1 2 1 2]
 [3 4 3 4 3 4]
 [1 2 1 2 1 2]
 [3 4 3 4 3 4]]
