In [173]:
import numpy as np

## 1.2 Создание массива

<img src="https://ucarecdn.com/09b174e8-e8b2-4c10-990c-570057daf8c8/" alt="drawing" width="400"/>.
<img src="https://ucarecdn.com/a659ae99-e9f5-4523-be7d-eae05bfbf195/" alt="drawing" width="600"/>.
<img src="https://ucarecdn.com/06e69802-f635-45dc-a3a9-95337ce1a6b8/" width="800"/>.
<img src="https://ucarecdn.com/1450cdcd-22ac-40e0-86ef-05ff27bf8510/" width="400"/>.

In [174]:
a = np.array([1,2,3])
b = np.array(([1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]), dtype=np.float64)
c = np.zeros((3,5))
d = np.ones((1,5))
print(a)
print(b)
print(c)
print(d)

[1 2 3]
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]]


In [175]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [176]:
np.arange(1,5)

array([1, 2, 3, 4])

In [177]:
print(np.arange(0,1 + 0.1,0.1))


[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [178]:
print(np.linspace(0,1)) # num (необязательный): Количество элементов в массиве. По умолчанию 50.

[0.         0.02040816 0.04081633 0.06122449 0.08163265 0.10204082
 0.12244898 0.14285714 0.16326531 0.18367347 0.20408163 0.2244898
 0.24489796 0.26530612 0.28571429 0.30612245 0.32653061 0.34693878
 0.36734694 0.3877551  0.40816327 0.42857143 0.44897959 0.46938776
 0.48979592 0.51020408 0.53061224 0.55102041 0.57142857 0.59183673
 0.6122449  0.63265306 0.65306122 0.67346939 0.69387755 0.71428571
 0.73469388 0.75510204 0.7755102  0.79591837 0.81632653 0.83673469
 0.85714286 0.87755102 0.89795918 0.91836735 0.93877551 0.95918367
 0.97959184 1.        ]


In [179]:
np.linspace(0,5,9)

array([0.   , 0.625, 1.25 , 1.875, 2.5  , 3.125, 3.75 , 4.375, 5.   ])

In [180]:
np.full((3,3),7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [181]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## 1.3 Создание массива часть 2

In [182]:
np.ones([3,2])

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

<img src="https://ucarecdn.com/c6cf7ceb-9a35-4001-9410-2259da43d47c/" width="600"/>.
<img src="https://ucarecdn.com/c544842a-29cd-48d8-b4a6-1d139228f5d3/" width="300"/>.

In [183]:
print(b)
print(np.ndim(b))
print(np.shape(b))
print(np.size(b))

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]
2
(4, 4)
16


In [184]:
print(np.eye(5,3)) # Еденичная матрица
print(np.eye(3,3)) # аналогично identity
print(np.identity(3)) # создает квадратную матрицу с единицами на главной диагонали и нулями в остальных местах.
# В отличие от numpy.identity,  numpy.eye позволяет создавать матрицы с единичной диагональю 
# произвольной размерности и выполнять сдвиг этой диагонали относительно главной диагонали.
print('')
print(np.eye(5,k=2))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [185]:
np.random.rand( 3,3 )

array([[0.35600555, 0.90128446, 0.8515309 ],
       [0.09619589, 0.34084397, 0.40681872],
       [0.76354926, 0.67983877, 0.83631927]])

In [186]:
np.random.randint(10) # случайное число от 0 до 10 (целое)

1

In [187]:
print(np.random.randint(1,10, size=5))

[7 3 5 8 6]


In [188]:
print(np.random.randint(1,10, size=(3,3)))

[[3 2 8]
 [1 1 8]
 [5 8 7]]


In [189]:
small_arr = np.array([[1,2],[3,4]])
small_arr

array([[1, 2],
       [3, 4]])

In [190]:
print(np.tile(small_arr,reps=3))

[[1 2 1 2 1 2]
 [3 4 3 4 3 4]]


In [191]:
print(np.tile(small_arr,reps=(3,3)))

[[1 2 1 2 1 2]
 [3 4 3 4 3 4]
 [1 2 1 2 1 2]
 [3 4 3 4 3 4]
 [1 2 1 2 1 2]
 [3 4 3 4 3 4]]


## 1.4 Типы Данных

int(16-64), float(16-64), complex(64-128), bool, string, object (используется для хранения произвольных объектов Python в массивах NumPy)

In [192]:
print(b*0.2)
print(np.dtype(b[0][0]))
b.dtype

[[0.2 0.4 0.6 0.8]
 [1.  1.2 1.4 1.6]
 [1.8 2.  2.2 2.4]
 [2.6 2.8 3.  3.2]]
float64


dtype('float64')

In [193]:
# array.astype(dtype, order='K', casting='unsafe', subok=True, copy=True)
b_int = (b*0.2).astype(np.int64)
print(b_int)
b.dtype

[[0 0 0 0]
 [1 1 1 1]
 [1 2 2 2]
 [2 2 3 3]]


dtype('float64')

Задача: Предположим, у вас есть два датасета с данными о температуре и влажности. Каждый датасет представлен в виде двумерного массива, где строки представляют дни, а столбцы представляют конкретные моменты времени в течение дня. Тип данных - int. Но вам нужно изменить их на float.

In [194]:
# put your python code here
import numpy as np

# Датасет температуры (тип данных: int)
temp_data = np.array([[22, 25, 24, 23, 21],
                      [20, 18, 19, 22, 24]])

# Датасет влажности (тип данных: int)
humid_data = np.array([[45, 50, 48, 52, 47],
                       [45, 48, 50, 51, 53]])

def change_data_type(data_set: np.array, data_type: np.dtype):  # добавь два аргумента для функции согласно условию
    return  data_set.astype(data_type)

temp_data =  change_data_type(temp_data, np.float64)
humid_data =  change_data_type(humid_data, np.float64)

print(f'Новый тип данных temp_data: {temp_data.dtype}')
print(f'Новый тип данных humid_data: {humid_data.dtype}')

Новый тип данных temp_data: float64
Новый тип данных humid_data: float64


In [195]:
arr = np.array([1, 'a', True, (2, 3), [4, 5]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (5,) + inhomogeneous part.

В NumPy, тип данных object представляет собой общий и гибкий тип, который может хранить объекты произвольного типа. Когда массив имеет тип данных object, это означает, что элементы массива могут быть любого типа данных, и каждый элемент массива фактически является объектом Python.

In [196]:
arr = np.array([1, 'a', True, (2, 3), [4, 5]], dtype=object)
arr

array([1, 'a', True, (2, 3), list([4, 5])], dtype=object)

## 1.5 Арифметические операции с массивами
<img src="https://ucarecdn.com/f1a8b477-8350-4933-808f-d7c18ab5b2bc/" width=1300>.
<img src="https://ucarecdn.com/1babf19f-aa71-4730-b7dd-9bfe173b4e91/" width=700>.
**Где @ - краткая форма записи матричного умножения (np.matmul)**

In [197]:
print(a)
print(b)

[1 2 3]
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]


In [198]:
a + b

ValueError: operands could not be broadcast together with shapes (3,) (4,4) 

In [199]:
a * b

ValueError: operands could not be broadcast together with shapes (3,) (4,4) 

In [200]:
5 * b

array([[ 5., 10., 15., 20.],
       [25., 30., 35., 40.],
       [45., 50., 55., 60.],
       [65., 70., 75., 80.]])

In [201]:
b_copy = b * 10
b + b_copy

array([[ 11.,  22.,  33.,  44.],
       [ 55.,  66.,  77.,  88.],
       [ 99., 110., 121., 132.],
       [143., 154., 165., 176.]])

In [202]:
print(b @ b_copy)

[[ 900. 1000. 1100. 1200.]
 [2020. 2280. 2540. 2800.]
 [3140. 3560. 3980. 4400.]
 [4260. 4840. 5420. 6000.]]


In [203]:
print(b * b_copy)

[[  10.   40.   90.  160.]
 [ 250.  360.  490.  640.]
 [ 810. 1000. 1210. 1440.]
 [1690. 1960. 2250. 2560.]]


In [204]:
print(a)
print(a * 5)

[1 2 3]
[ 5 10 15]


In [205]:
b_copy = b[1: , 1:] # сделали 3x3
print(b_copy)
print(a + b_copy) # построчное сложение

[[ 6.  7.  8.]
 [10. 11. 12.]
 [14. 15. 16.]]
[[ 7.  9. 11.]
 [11. 13. 15.]
 [15. 17. 19.]]


In [206]:
print(a + a*-1)

[0 0 0]


In [207]:
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

arr1 / 4

array([[0.25, 0.5 , 0.75],
       [1.  , 1.25, 1.5 ],
       [1.75, 2.  , 2.25]])

In [208]:
arr1 ** 2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [209]:
np.where(arr1 < 5, a , a*1000) # if statement, YES cond, NO cond

array([[   1,    2,    3],
       [   1, 2000, 3000],
       [1000, 2000, 3000]])

In [210]:
matrix_a = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

vec_b = np.array([10,20,30]).reshape(3,1) # создайте вектор-столбец


print(matrix_a*vec_b)

[[ 10  20  30]
 [ 80 100 120]
 [210 240 270]]


## 1.6 Индексы и срезы

1.Slicing (cлайсинг/срез) в NumPy работает аналогично срезу в стандартном Python, но с добавлением некоторых особенностей для работы с многомерными массивами. Основные параметры среза в NumPy:

arr[start:stop:step]

    start: Начальный индекс среза. Элемент с этим индексом включается в срез.
    stop: Конечный индекс среза. Элемент с этим индексом не включается в срез.
    step: Шаг (или интервал) между выбранными элементами. Если не указан, используется шаг 1.

Некоторые важные замечания:

    Если start не указан, используется начало массива (индекс 0).
    Если stop не указан, используется конец массива (последний элемент).
    Если step не указан, используется шаг 1.
    Все эти параметры могут быть отрицательными, что означает выбор элементов в обратном порядке.
    В случае отрицательного step и отсутствия start и stop, массив будет выведен в обратном порядке.
<img src="https://ucarecdn.com/d82e7acf-1719-4d9b-a7c6-60d43de4c4f4/" width=1200>


In [211]:
a = np.array([1,2,3,4,5,6,7])
print(a[4:123]) # OUT OF RANGE WONT GIVE YOU AN ERROR!

[5 6 7]


<img src="https://ucarecdn.com/b175cafe-a492-42c9-b3ae-c02f342a0981/" width=900>.
<img src="https://ucarecdn.com/d6258be9-27f9-4b9a-983a-6f2c3719c916/" width=900>.

In [212]:
b

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.],
       [13., 14., 15., 16.]])

In [213]:
b[1:2]

array([[5., 6., 7., 8.]])

In [214]:
b[1:2 , 1:3]

array([[6., 7.]])

In [215]:
b[: , 1:3]

array([[ 2.,  3.],
       [ 6.,  7.],
       [10., 11.],
       [14., 15.]])

In [216]:
b[: , 0]

array([ 1.,  5.,  9., 13.])

 <img src="https://ucarecdn.com/d15c0cbd-de5a-46ce-81fc-17edf40b9d13/" width=700>.

В NumPy различие между ```[:, :, 1] и [:, :, 1:2]``` заключается в форме итогового массива (слайса).

```[:, :, 1]```: Этот срез возвращает одномерный массив, выбирая второй столбец для каждой строки в каждой матрице. Результат - одномерный массив с элементами из второго столбца для каждой строки

Результат 
```
[:, :, 1:2]:
[[[ 2]
  [ 5]
  [ 8]]

 [[11]
  [14]
  [17]]

 [[20]
  [23]
  [26]]]
```
```[:, :, 1:2]```: Этот срез возвращает двумерный массив, выбирая второй столбец в виде двумерного среза. Результат - двумерный массив с элементами из второго столбца для каждой строки, но он сохраняет второй столбец как отдельное измерение. Размерность будет (3, 3, 1).
Результат ```[:, :, 1]```:
```
[[ 2  5  8]
 [11 14 17]
 [20 23 26]]
```

## 1.7 Основы Boolean Indexing:

Индексация по булевым значениям в Numpy — это механизм выбора элементов из массива на основе булевых условий. Это позволяет создавать условные выражения для фильтрации данных.

Можно создать булев массив такой же формы, что и исходный массив, применяя условные операции к элементам.
<img src="https://ucarecdn.com/9abcc990-3872-430a-8923-a91cc57db1c6/" width=800>

In [217]:
print(b)
b_even = ((b+1)%2) # все четные элементы внутри b
# not(b%2) или !(b%2) не сработает!
# НО! (b%2==0) заработает
print(b_even)

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]
[[0. 1. 0. 1.]
 [0. 1. 0. 1.]
 [0. 1. 0. 1.]
 [0. 1. 0. 1.]]


Булев массив может быть использован как индекс для выбора элементов из массива, соответствующих True значениям в булевом массиве.

In [218]:
print(b[ b > 5 ]) # Возвращает строку

[ 6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16.]


Можно комбинировать несколько условий с использованием операторов ```&``` (и), ```|``` (или), ```~``` (не).

Затем этот булев массив может быть использован для выбора соответствующих элементов из исходного массива или замены значений.

***Не заработает внутри ```arr[ arr > 2 & arr < 6 ]``` , используйте скобки ```arr[(arr > 2) & (arr < 6)]```***

In [219]:
comb_cond = (b % 2 ==0) & (b < 10) # b % 2 без указания остатка (==) не заработает
print(b[comb_cond])

[2. 4. 6. 8.]


Функция ```np.any``` используется для проверки, есть ли хотя бы один элемент в массиве, который оценивается как True.
```numpy.any(a, axis=None)```
```a```: Исходный массив.
```axis```: Опциональный параметр, определяющий по какой оси выполняется проверка. Если ```None``` (по умолчанию), то проверка выполняется по всем элементам массива.

In [220]:
np.any(b < 0) # провекрка каждого элемента

False

In [221]:
print(np.any(b > 10, axis=1)) # только в 2ой и 3ей строках есть элемент больше 10
print(b)

[False False  True  True]
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]


In [222]:
print(np.all(b < 14, axis=0)) # только в первом столбце все элементы меньше 14
print(b)

[ True False False False]
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]


<img src="https://ucarecdn.com/5e9e6486-78bf-4b95-81f1-4f423385651f/">.
<img src="https://ucarecdn.com/86098fbc-585a-4154-8d50-37742b8f4d03/">

In [223]:
print(b)

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]


In [224]:
b_copy = np.array(b, copy=True)
b_copy[ 1:3 , 1:3]  = -1
print(b_copy)

[[ 1.  2.  3.  4.]
 [ 5. -1. -1.  8.]
 [ 9. -1. -1. 12.]
 [13. 14. 15. 16.]]


In [225]:
b_copy = np.array(b, copy=True)
b_copy[ b_copy[ : , 1] > 6, 1] = -1000
print(b_copy)

[[    1.     2.     3.     4.]
 [    5.     6.     7.     8.]
 [    9. -1000.    11.    12.]
 [   13. -1000.    15.    16.]]


Если есть 2 массива - один с условием, втрой со значениями, то можно использовать ```np.where( условие , если да , в каком массиве менять )```

In [242]:
index_arr = np.array([1,0,1,0,1,1,0])
a = np.array([1, 2, 3, 4, 5, 6, 7])
print(a)
print(np.where(index_arr == True, -1 , a))
print(a [index_arr == False])

[1 2 3 4 5 6 7]
[-1  2 -1  4 -1 -1  7]
[2 4 7]


*Задача*: Представим, у вас есть массив чисел, и вы хотите проверить, содержит ли он хотя бы одно положительное число и все ли элементы отрицательны. Необходимо проверить это с помощью функции check_array.

In [247]:
# put your python code here
import numpy as np

def check_array(arr):
    has_positive =  np.any(arr > 0)
    all_negative =  np.all(arr < 0)

    return  has_positive , all_negative# функция должна возвращать два булева значения 

array2 = np.array([-2, -4, -6, -8, -1])
result = check_array(array2)

print(f"В массиве есть хотя бы одно положительное число: {result[0]}")
print(f"Все элементы массива отрицательны: {result[1]}")

В массиве есть хотя бы одно положительное число: False
Все элементы массива отрицательны: True


Задача: Предположим, у вас есть набор данных о продажах товаров, представленный в виде двумерного массива sales_data_array. Каждая строка представляет собой информацию о продажах для конкретного товара, а столбцы содержат следующую информацию: номер товара, количество проданных единиц, и доход от продаж.

Ваша задача - проверить следующие условия:

>Есть ли хотя бы одна запись с нулевыми продажами (количество проданных единиц равно 0)?
>Все ли товары имеют положительный доход от продаж?


In [248]:
# put your python code here
import numpy as np

sales_data_array = np.array([[1, 10, 100],
                             [2, 5, 50],
                             [3, 0, 0],
                             [4, 8, 80]])

def analyze_sales_data(sales_data):
    has_zero_sales =  np.any(sales_data[ : , 1] <= 0)
    all_positive_income = np.all(sales_data[ : , 2] > 0)

    return  has_zero_sales, all_positive_income

result =  analyze_sales_data(sales_data_array)# проверь массив sales_data_array с помощью функции analyze_sales_data

print(f"Есть ли товары с нулевыми продажами: {result[0]}")  # первое булево значение согласно условию
print(f"Все ли товары имеют положительный доход: {result[1]}")  # второе булево значение согласно условию

Есть ли товары с нулевыми продажами: True
Все ли товары имеют положительный доход: True


Задача: Дан массив data размером 5 x 5, заполненный случайными целыми числами от 0 до 9. Замените все четные числа в массиве на 0, а все нечетные на 1. Используйте булеву индексацию для создания масок, которые соответствуют этим условиям, и примените их к массиву data.  

``` 
Sample Output:

[[0 0 0 1 1]
 [0 0 1 1 0]
 [1 1 1 0 0]
 [1 1 0 0 0]
 [1 0 1 0 1]]
```

In [260]:
# put your python code here
import numpy as np

data = np.array([[6, 4, 8, 7, 9],
                 [0, 0, 1, 7, 2],
                 [5, 7, 9, 0, 4],
                 [5, 1, 2, 8, 6],
                 [9, 8, 3, 0, 3]])

even_mask =  data [ data %2 == 0 ] # Одномерный массив из ЭЛЕМЕНТОВ 
odd_mask = data %2 == 1 # двумерная булевая матрица
print(even_mask)
print(odd_mask)

data = np.where(data % 2 == 0 , 0 , data) # Меняем элементы без Маски (ДВУМЕРНЫЙ БУЛЕВОЙ МАССИВ)
data[odd_mask] = 1 # Используем маску

data

[6 4 8 0 0 2 0 4 2 8 6 8 0]
[[False False False  True  True]
 [False False  True  True False]
 [ True  True  True False False]
 [ True  True False False False]
 [ True False  True False  True]]


array([[0, 0, 0, 1, 1],
       [0, 0, 1, 1, 0],
       [1, 1, 1, 0, 0],
       [1, 1, 0, 0, 0],
       [1, 0, 1, 0, 1]])

Задача: Дан массив data размером 6 x 6, заполненный случайными целыми числами от 0 до 9. Найдите среднее арифметическое всех элементов, которые находятся на главной диагонали массива. Используйте булеву индексацию для создания маски, которая соответствует этому условию, и примените ее к массиву data

In [276]:
# put your python code here
import numpy as np

data = np.array([[8, 3, 9, 1, 9, 0],
                 [5, 4, 2, 7, 4, 2],
                 [0, 8, 7, 4, 3, 9],
                 [0, 9, 7, 1, 0, 1],
                 [7, 1, 0, 3, 9, 3],
                 [5, 8, 0, 4, 0, 6]])

mask = np.eye(np.shape(data)[0],dtype=bool)

mean = np.mean(data[mask])

print(f'Среднее арифметическое элементов на диагоналях: {mean:.2f}')

Среднее арифметическое элементов на диагоналях: 5.83


Задача: Попробуем с настоящими данными. Дан массив data, содержащий информацию о студентах: имя, возраст, пол, курс и средний балл. Найдите имена, средние баллы и другую информацию студентов, которые старше 20 лет, женского пола и учатся на третьем курсе. Используйте булеву индексацию для создания маски, которая соответствует этому условию, и примените ее к массиву data.  

In [284]:
# put your python code here
import numpy as np

data = np.array([
    ['Анна', 19, 'F', 1, 4.5],
    ['Борис', 21, 'M', 2, 3.7],
    ['Вера', 21, 'F', 3, 4.8],
    ['Глеб', 22, 'M', 4, 3.9],
    ['Дарья', 18, 'F', 1, 4.2],
    ['Егор', 23, 'M', 3, 4.1],
    ['Жанна', 21, 'F', 2, 4.6],
    ['Захар', 19, 'M', 1, 4.0]
])

mask = (data[: , 1].astype(int) > 20) & (data[ : , 2] == 'F') & (data[ : , 3].astype(int) == 3)

result = data[mask]

print(result)

[['Вера' '21' 'F' '3' '4.8']]


## 1.8 Транспонирование Массивов